### ISSUE TITLE
Error: Expected 4 octets in '...an-IPv6-adress-is-shown-here...'

### ISSUE THREAD

**Issue by DocSniper** [lopsided98/dnsupdate#3]
I get the error below and the IPv4 address of service 0 (NSUpdate) isn't updated:
```
$ sudo systemctl status dnsupdate.service
dnsupdate.service - Run dynamic DNS update client
Loaded: loaded (/usr/lib/systemd/system/dnsupdate.service; enabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Mon 2021-02-22 09:05:13 CET; 2s ago
TriggeredBy: dnsupdate.timer
Process: 12808 ExecStart=/usr/bin/dnsupdate (code=exited, status=3)
Main PID: 12808 (code=exited, status=3)

dnsupdate: Error: Expected 4 octets in '1111:2222:3333:4444:5555:6666:7777:8888'
dnsupdate: Updating IPv4 address of service 0 (NSUpdate [domain0])...
dnsupdate: Updating IPv6 address of service 0 (NSUpdate [domain0])...
dnsupdate: Address has not changed, no update needed.
dnsupdate: Updating IPv4 address of service 1 (FreeDNS)...
dnsupdate: Updating IPv6 address of service 1 (FreeDNS)...
dnsupdate: Address has not changed, no update needed.
systemd: dnsupdate.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
systemd: dnsupdate.service: Failed with result 'exit-code'.
systemd: Failed to start Run dynamic DNS update client.
```
"Expected 4 octets" indicates to me that dnsupdate mistakenly uses the IPv6 address to determine the actual IPv4 address ?!

**Comment by lopsided98** [comment]
I think this is coming from the address provider. Are you using the default address provider (`Web`, which uses `https://icanhazip.com/` by default)? If so, could you check that `curl https://ipv4.icanhazip.com/` returns an IPv4 address? Make sure you run that command on the same machine you are running `dnsupdate` on.

**Comment by DocSniper** [comment]
Yes I have almost everything on default, my config looks like this:
```
dns_services:
    - type: NSUpdate
      args:
          hostname: some_host_name
          secret_key: the_key
    - type: FreeDNS
      args:
          ipv4_key: the_v4_key
          ipv6_key: the_v6_key
```
Tonight, during the DSL reconnect, everything suddenly worked again. The update worked without errors.
I entered the command `curl https://ipv4.icanhazip.com/` before and got an IPv4 address. 
Yesterday, of course, I don't know, but there I had entered the command `ip a` and saw that the interface had both an IPv4 and an IPv6 address. I have dual stack and so an official IPv4 address as well as IPv6 address.

**Comment by lopsided98** [comment]
`dnsupdate` should work fine with dual stack; that's actually part of the reason I wrote it. `ipv4.icanhazip.com` should only resolve to an IPv4 address, and therefore show your IPv4 address even if you have an IPv6 address as well. Off the top of my head, I can't think of a reason for that error other than `ipv4.icanhazip.com` somehow returning a IPv6 address.

If it happens again, run `curl https://ipv4.icanhazip.com/` and `drill ipv4.icanhazip.com` (or `dig` if that is available on your system instead) to try to see what is happening.

**Comment by DocSniper** [comment]
Yes, very well possible that it was exactly like that. 
Because the error occurred only 5 days and disappeared as suddenly as it had come.
Thanks for the reply :-)

**Comment by DocSniper** [comment]
The error just appears again. 
I used curl and noticed that when I use `curl -6 https://ipv4.icanhazip.com/` I get an IPv6 address and 
when I use `curl -4 https://ipv6.icanhazip.com/` I get an IPv4 address. 
Is it possible to force the IP version in Python when doing these queries?

**Comment by lopsided98** [comment]
There is an open issue about this: https://github.com/major/icanhaz/issues/31. I'll look into workarounds, but unfortunately there doesn't seem to be a non-hacky way to force `requests` to use a particular protocol.

**Comment by lopsided98** [comment]
This should be fixed in master.
